main: me.barnaby.movingholograms.MovingHolograms
name: MovingHolograms
author: Barnaby
api-version: 1.20
version: 1.0.0
depend:
  - DecentHolograms
commands:
  movingholograms:
    aliases: [roguetracker, tracker]